arch:
        #  - amd64
  - ppc64le
distro: focal 
language: node_js
node_js:
  - "12"
    #  - "11"
    #  - "10"
before_install:
  - |
   if [[ "$TRAVIS_CPU_ARCH" == "ppc64le" ]]; then
     sudo apt-get install libmali-xlnx libmali-xlnx-dev packagegroup-petalinux-x11-dev
     export QT_QPA_PLATFORM=offscreen
     sudo apt-get install phantomjs
   fi
script:
 - npm test
 - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
